version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: online_store
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: online_store
    volumes:
      - db_data:/var/lib/mysql
      - ./online_store.sql:/docker-entrypoint-initdb.d/online_store.sql

volumes:
  db_data:
